#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MediaManager.Android.Resource", IsApplication=false)]

namespace MediaManager.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int ad_marker_color = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int ad_marker_width = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int alpha = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int auto_show = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int bar_height = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int buffered_color = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int controller_layout_id = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int default_artwork = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int fastforward_increment = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int font = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public static int fontProviderAuthority = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public static int fontProviderCerts = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public static int fontProviderFetchStrategy = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public static int fontProviderFetchTimeout = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public static int fontProviderPackage = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public static int fontProviderQuery = 2130771983;
			
			// aapt resource value: 0x7F010010
			public static int fontStyle = 2130771984;
			
			// aapt resource value: 0x7F010011
			public static int fontVariationSettings = 2130771985;
			
			// aapt resource value: 0x7F010012
			public static int fontWeight = 2130771986;
			
			// aapt resource value: 0x7F010013
			public static int hide_during_ads = 2130771987;
			
			// aapt resource value: 0x7F010014
			public static int hide_on_touch = 2130771988;
			
			// aapt resource value: 0x7F010015
			public static int keep_content_on_player_reset = 2130771989;
			
			// aapt resource value: 0x7F010016
			public static int played_ad_marker_color = 2130771990;
			
			// aapt resource value: 0x7F010017
			public static int played_color = 2130771991;
			
			// aapt resource value: 0x7F010018
			public static int player_layout_id = 2130771992;
			
			// aapt resource value: 0x7F010019
			public static int repeat_toggle_modes = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public static int resize_mode = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public static int rewind_increment = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public static int scrubber_color = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public static int scrubber_disabled_size = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public static int scrubber_dragged_size = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public static int scrubber_drawable = 2130771999;
			
			// aapt resource value: 0x7F010020
			public static int scrubber_enabled_size = 2130772000;
			
			// aapt resource value: 0x7F010021
			public static int show_buffering = 2130772001;
			
			// aapt resource value: 0x7F010022
			public static int show_shuffle_button = 2130772002;
			
			// aapt resource value: 0x7F010023
			public static int show_timeout = 2130772003;
			
			// aapt resource value: 0x7F010024
			public static int shutter_background_color = 2130772004;
			
			// aapt resource value: 0x7F010025
			public static int surface_type = 2130772005;
			
			// aapt resource value: 0x7F010026
			public static int time_bar_min_update_interval = 2130772006;
			
			// aapt resource value: 0x7F010027
			public static int touch_target_height = 2130772007;
			
			// aapt resource value: 0x7F010028
			public static int ttcIndex = 2130772008;
			
			// aapt resource value: 0x7F010029
			public static int unplayed_color = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public static int use_artwork = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public static int use_controller = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public static int use_sensor_rotation = 2130772012;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public static int exo_edit_mode_background_color = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int exo_error_message_background_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int notification_action_color_filter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int notification_icon_bg_color = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int notification_material_background_media_default_color = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int primary_text_default_material_dark = 2130837509;
			
			// aapt resource value: 0x7F020006
			public static int ripple_material_light = 2130837510;
			
			// aapt resource value: 0x7F020007
			public static int secondary_text_default_material_dark = 2130837511;
			
			// aapt resource value: 0x7F020008
			public static int secondary_text_default_material_light = 2130837512;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public static int compat_button_inset_horizontal_material = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int compat_button_inset_vertical_material = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int compat_button_padding_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int compat_button_padding_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int compat_control_corner_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int compat_notification_large_icon_max_height = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int compat_notification_large_icon_max_width = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int exo_media_button_height = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int exo_media_button_width = 2130903048;
			
			// aapt resource value: 0x7F030009
			public static int notification_action_icon_size = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public static int notification_action_text_size = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public static int notification_big_circle_margin = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public static int notification_content_margin_start = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public static int notification_large_icon_height = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public static int notification_large_icon_width = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public static int notification_main_column_padding_top = 2130903055;
			
			// aapt resource value: 0x7F030010
			public static int notification_media_narrow_margin = 2130903056;
			
			// aapt resource value: 0x7F030011
			public static int notification_right_icon_size = 2130903057;
			
			// aapt resource value: 0x7F030012
			public static int notification_right_side_padding_top = 2130903058;
			
			// aapt resource value: 0x7F030013
			public static int notification_small_icon_background_padding = 2130903059;
			
			// aapt resource value: 0x7F030014
			public static int notification_small_icon_size_as_large = 2130903060;
			
			// aapt resource value: 0x7F030015
			public static int notification_subtext_size = 2130903061;
			
			// aapt resource value: 0x7F030016
			public static int notification_top_pad = 2130903062;
			
			// aapt resource value: 0x7F030017
			public static int notification_top_pad_large_text = 2130903063;
			
			// aapt resource value: 0x7F030018
			public static int subtitle_corner_radius = 2130903064;
			
			// aapt resource value: 0x7F030019
			public static int subtitle_outline_width = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public static int subtitle_shadow_offset = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public static int subtitle_shadow_radius = 2130903067;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public static int exo_controls_fastforward = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int exo_controls_fullscreen_enter = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int exo_controls_fullscreen_exit = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int exo_controls_next = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int exo_controls_pause = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int exo_controls_play = 2130968581;
			
			// aapt resource value: 0x7F040006
			public static int exo_controls_previous = 2130968582;
			
			// aapt resource value: 0x7F040007
			public static int exo_controls_repeat_all = 2130968583;
			
			// aapt resource value: 0x7F040008
			public static int exo_controls_repeat_off = 2130968584;
			
			// aapt resource value: 0x7F040009
			public static int exo_controls_repeat_one = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public static int exo_controls_rewind = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public static int exo_controls_shuffle_off = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public static int exo_controls_shuffle_on = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public static int exo_controls_vr = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public static int exo_edit_mode_logo = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public static int exo_icon_circular_play = 2130968591;
			
			// aapt resource value: 0x7F040010
			public static int exo_icon_fastforward = 2130968592;
			
			// aapt resource value: 0x7F040011
			public static int exo_icon_fullscreen_enter = 2130968593;
			
			// aapt resource value: 0x7F040012
			public static int exo_icon_fullscreen_exit = 2130968594;
			
			// aapt resource value: 0x7F040013
			public static int exo_icon_next = 2130968595;
			
			// aapt resource value: 0x7F040014
			public static int exo_icon_pause = 2130968596;
			
			// aapt resource value: 0x7F040015
			public static int exo_icon_play = 2130968597;
			
			// aapt resource value: 0x7F040016
			public static int exo_icon_previous = 2130968598;
			
			// aapt resource value: 0x7F040017
			public static int exo_icon_repeat_all = 2130968599;
			
			// aapt resource value: 0x7F040018
			public static int exo_icon_repeat_off = 2130968600;
			
			// aapt resource value: 0x7F040019
			public static int exo_icon_repeat_one = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public static int exo_icon_rewind = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public static int exo_icon_shuffle_off = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public static int exo_icon_shuffle_on = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public static int exo_icon_stop = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public static int exo_icon_vr = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public static int exo_media_action_repeat_all = 2130968607;
			
			// aapt resource value: 0x7F040020
			public static int exo_media_action_repeat_off = 2130968608;
			
			// aapt resource value: 0x7F040021
			public static int exo_media_action_repeat_one = 2130968609;
			
			// aapt resource value: 0x7F040022
			public static int exo_notification_fastforward = 2130968610;
			
			// aapt resource value: 0x7F040023
			public static int exo_notification_next = 2130968611;
			
			// aapt resource value: 0x7F040024
			public static int exo_notification_pause = 2130968612;
			
			// aapt resource value: 0x7F040025
			public static int exo_notification_play = 2130968613;
			
			// aapt resource value: 0x7F040026
			public static int exo_notification_previous = 2130968614;
			
			// aapt resource value: 0x7F040027
			public static int exo_notification_rewind = 2130968615;
			
			// aapt resource value: 0x7F040028
			public static int exo_notification_small_icon = 2130968616;
			
			// aapt resource value: 0x7F040029
			public static int exo_notification_stop = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public static int notification_action_background = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public static int notification_bg = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public static int notification_bg_low = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public static int notification_bg_low_normal = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public static int notification_bg_low_pressed = 2130968622;
			
			// aapt resource value: 0x7F04002F
			public static int notification_bg_normal = 2130968623;
			
			// aapt resource value: 0x7F040030
			public static int notification_bg_normal_pressed = 2130968624;
			
			// aapt resource value: 0x7F040031
			public static int notification_icon_background = 2130968625;
			
			// aapt resource value: 0x7F040032
			public static int notification_template_icon_bg = 2130968626;
			
			// aapt resource value: 0x7F040033
			public static int notification_template_icon_low_bg = 2130968627;
			
			// aapt resource value: 0x7F040034
			public static int notification_tile_bg = 2130968628;
			
			// aapt resource value: 0x7F040035
			public static int notify_panel_notification_icon_bg = 2130968629;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public static int accessibility_action_clickable_span = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int accessibility_custom_action_0 = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int accessibility_custom_action_1 = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int accessibility_custom_action_10 = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int accessibility_custom_action_11 = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int accessibility_custom_action_12 = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int accessibility_custom_action_13 = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int accessibility_custom_action_14 = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int accessibility_custom_action_15 = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int accessibility_custom_action_16 = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int accessibility_custom_action_17 = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int accessibility_custom_action_18 = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int accessibility_custom_action_19 = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int accessibility_custom_action_2 = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int accessibility_custom_action_20 = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int accessibility_custom_action_21 = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int accessibility_custom_action_22 = 2131034128;
			
			// aapt resource value: 0x7F050011
			public static int accessibility_custom_action_23 = 2131034129;
			
			// aapt resource value: 0x7F050012
			public static int accessibility_custom_action_24 = 2131034130;
			
			// aapt resource value: 0x7F050013
			public static int accessibility_custom_action_25 = 2131034131;
			
			// aapt resource value: 0x7F050014
			public static int accessibility_custom_action_26 = 2131034132;
			
			// aapt resource value: 0x7F050015
			public static int accessibility_custom_action_27 = 2131034133;
			
			// aapt resource value: 0x7F050016
			public static int accessibility_custom_action_28 = 2131034134;
			
			// aapt resource value: 0x7F050017
			public static int accessibility_custom_action_29 = 2131034135;
			
			// aapt resource value: 0x7F050018
			public static int accessibility_custom_action_3 = 2131034136;
			
			// aapt resource value: 0x7F050019
			public static int accessibility_custom_action_30 = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public static int accessibility_custom_action_31 = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public static int accessibility_custom_action_4 = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public static int accessibility_custom_action_5 = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public static int accessibility_custom_action_6 = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public static int accessibility_custom_action_7 = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public static int accessibility_custom_action_8 = 2131034143;
			
			// aapt resource value: 0x7F050020
			public static int accessibility_custom_action_9 = 2131034144;
			
			// aapt resource value: 0x7F050021
			public static int action0 = 2131034145;
			
			// aapt resource value: 0x7F050026
			public static int actions = 2131034150;
			
			// aapt resource value: 0x7F050022
			public static int action_container = 2131034146;
			
			// aapt resource value: 0x7F050023
			public static int action_divider = 2131034147;
			
			// aapt resource value: 0x7F050024
			public static int action_image = 2131034148;
			
			// aapt resource value: 0x7F050025
			public static int action_text = 2131034149;
			
			// aapt resource value: 0x7F050027
			public static int all = 2131034151;
			
			// aapt resource value: 0x7F050028
			public static int always = 2131034152;
			
			// aapt resource value: 0x7F050029
			public static int async = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public static int blocking = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public static int cancel_action = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public static int chronometer = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public static int dialog_button = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public static int end_padder = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public static int exo_ad_overlay = 2131034159;
			
			// aapt resource value: 0x7F050030
			public static int exo_artwork = 2131034160;
			
			// aapt resource value: 0x7F050031
			public static int exo_buffering = 2131034161;
			
			// aapt resource value: 0x7F050032
			public static int exo_content_frame = 2131034162;
			
			// aapt resource value: 0x7F050033
			public static int exo_controller = 2131034163;
			
			// aapt resource value: 0x7F050034
			public static int exo_controller_placeholder = 2131034164;
			
			// aapt resource value: 0x7F050035
			public static int exo_duration = 2131034165;
			
			// aapt resource value: 0x7F050036
			public static int exo_error_message = 2131034166;
			
			// aapt resource value: 0x7F050037
			public static int exo_ffwd = 2131034167;
			
			// aapt resource value: 0x7F050038
			public static int exo_next = 2131034168;
			
			// aapt resource value: 0x7F050039
			public static int exo_overlay = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public static int exo_pause = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public static int exo_play = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public static int exo_position = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public static int exo_prev = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public static int exo_progress = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public static int exo_progress_placeholder = 2131034175;
			
			// aapt resource value: 0x7F050040
			public static int exo_repeat_toggle = 2131034176;
			
			// aapt resource value: 0x7F050041
			public static int exo_rew = 2131034177;
			
			// aapt resource value: 0x7F050042
			public static int exo_shuffle = 2131034178;
			
			// aapt resource value: 0x7F050043
			public static int exo_shutter = 2131034179;
			
			// aapt resource value: 0x7F050044
			public static int exo_subtitles = 2131034180;
			
			// aapt resource value: 0x7F050045
			public static int exo_track_selection_view = 2131034181;
			
			// aapt resource value: 0x7F050046
			public static int exo_vr = 2131034182;
			
			// aapt resource value: 0x7F050047
			public static int fill = 2131034183;
			
			// aapt resource value: 0x7F050048
			public static int fit = 2131034184;
			
			// aapt resource value: 0x7F050049
			public static int fixed_height = 2131034185;
			
			// aapt resource value: 0x7F05004A
			public static int fixed_width = 2131034186;
			
			// aapt resource value: 0x7F05004B
			public static int forever = 2131034187;
			
			// aapt resource value: 0x7F05004C
			public static int icon = 2131034188;
			
			// aapt resource value: 0x7F05004D
			public static int icon_group = 2131034189;
			
			// aapt resource value: 0x7F05004E
			public static int info = 2131034190;
			
			// aapt resource value: 0x7F05004F
			public static int italic = 2131034191;
			
			// aapt resource value: 0x7F050050
			public static int line1 = 2131034192;
			
			// aapt resource value: 0x7F050051
			public static int line3 = 2131034193;
			
			// aapt resource value: 0x7F050052
			public static int media_actions = 2131034194;
			
			// aapt resource value: 0x7F050053
			public static int never = 2131034195;
			
			// aapt resource value: 0x7F050054
			public static int none = 2131034196;
			
			// aapt resource value: 0x7F050055
			public static int normal = 2131034197;
			
			// aapt resource value: 0x7F050056
			public static int notification_background = 2131034198;
			
			// aapt resource value: 0x7F050057
			public static int notification_main_column = 2131034199;
			
			// aapt resource value: 0x7F050058
			public static int notification_main_column_container = 2131034200;
			
			// aapt resource value: 0x7F050059
			public static int one = 2131034201;
			
			// aapt resource value: 0x7F05005A
			public static int right_icon = 2131034202;
			
			// aapt resource value: 0x7F05005B
			public static int right_side = 2131034203;
			
			// aapt resource value: 0x7F05005C
			public static int spherical_gl_surface_view = 2131034204;
			
			// aapt resource value: 0x7F05005D
			public static int status_bar_latest_event_content = 2131034205;
			
			// aapt resource value: 0x7F05005E
			public static int surface_view = 2131034206;
			
			// aapt resource value: 0x7F05005F
			public static int tag_accessibility_actions = 2131034207;
			
			// aapt resource value: 0x7F050060
			public static int tag_accessibility_clickable_spans = 2131034208;
			
			// aapt resource value: 0x7F050061
			public static int tag_accessibility_heading = 2131034209;
			
			// aapt resource value: 0x7F050062
			public static int tag_accessibility_pane_title = 2131034210;
			
			// aapt resource value: 0x7F050063
			public static int tag_screen_reader_focusable = 2131034211;
			
			// aapt resource value: 0x7F050064
			public static int tag_transition_group = 2131034212;
			
			// aapt resource value: 0x7F050065
			public static int tag_unhandled_key_event_manager = 2131034213;
			
			// aapt resource value: 0x7F050066
			public static int tag_unhandled_key_listeners = 2131034214;
			
			// aapt resource value: 0x7F050067
			public static int text = 2131034215;
			
			// aapt resource value: 0x7F050068
			public static int text2 = 2131034216;
			
			// aapt resource value: 0x7F050069
			public static int texture_view = 2131034217;
			
			// aapt resource value: 0x7F05006A
			public static int time = 2131034218;
			
			// aapt resource value: 0x7F05006B
			public static int title = 2131034219;
			
			// aapt resource value: 0x7F05006C
			public static int video_decoder_gl_surface_view = 2131034220;
			
			// aapt resource value: 0x7F05006D
			public static int when_playing = 2131034221;
			
			// aapt resource value: 0x7F05006E
			public static int zoom = 2131034222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public static int cancel_button_image_alpha = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int exo_media_button_opacity_percentage_disabled = 2131099649;
			
			// aapt resource value: 0x7F060002
			public static int exo_media_button_opacity_percentage_enabled = 2131099650;
			
			// aapt resource value: 0x7F060003
			public static int status_bar_notification_info_maxnum = 2131099651;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public static int custom_dialog = 2131165184;
			
			// aapt resource value: 0x7F070001
			public static int exo_list_divider = 2131165185;
			
			// aapt resource value: 0x7F070002
			public static int exo_playback_control_view = 2131165186;
			
			// aapt resource value: 0x7F070003
			public static int exo_player_control_view = 2131165187;
			
			// aapt resource value: 0x7F070004
			public static int exo_player_view = 2131165188;
			
			// aapt resource value: 0x7F070005
			public static int exo_simple_player_view = 2131165189;
			
			// aapt resource value: 0x7F070006
			public static int exo_track_selection_dialog = 2131165190;
			
			// aapt resource value: 0x7F070007
			public static int notification_action = 2131165191;
			
			// aapt resource value: 0x7F070008
			public static int notification_action_tombstone = 2131165192;
			
			// aapt resource value: 0x7F070009
			public static int notification_media_action = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public static int notification_media_cancel_action = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public static int notification_template_big_media = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public static int notification_template_big_media_custom = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public static int notification_template_big_media_narrow = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public static int notification_template_big_media_narrow_custom = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public static int notification_template_custom_big = 2131165199;
			
			// aapt resource value: 0x7F070010
			public static int notification_template_icon_group = 2131165200;
			
			// aapt resource value: 0x7F070011
			public static int notification_template_lines_media = 2131165201;
			
			// aapt resource value: 0x7F070012
			public static int notification_template_media = 2131165202;
			
			// aapt resource value: 0x7F070013
			public static int notification_template_media_custom = 2131165203;
			
			// aapt resource value: 0x7F070014
			public static int notification_template_part_chronometer = 2131165204;
			
			// aapt resource value: 0x7F070015
			public static int notification_template_part_time = 2131165205;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public static int app_name = 2131230720;
			
			// aapt resource value: 0x7F080001
			public static int exo_controls_fastforward_description = 2131230721;
			
			// aapt resource value: 0x7F080002
			public static int exo_controls_fullscreen_description = 2131230722;
			
			// aapt resource value: 0x7F080003
			public static int exo_controls_hide = 2131230723;
			
			// aapt resource value: 0x7F080004
			public static int exo_controls_next_description = 2131230724;
			
			// aapt resource value: 0x7F080005
			public static int exo_controls_pause_description = 2131230725;
			
			// aapt resource value: 0x7F080006
			public static int exo_controls_play_description = 2131230726;
			
			// aapt resource value: 0x7F080007
			public static int exo_controls_previous_description = 2131230727;
			
			// aapt resource value: 0x7F080008
			public static int exo_controls_repeat_all_description = 2131230728;
			
			// aapt resource value: 0x7F080009
			public static int exo_controls_repeat_off_description = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public static int exo_controls_repeat_one_description = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public static int exo_controls_rewind_description = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public static int exo_controls_show = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public static int exo_controls_shuffle_off_description = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public static int exo_controls_shuffle_on_description = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public static int exo_controls_stop_description = 2131230735;
			
			// aapt resource value: 0x7F080010
			public static int exo_controls_vr_description = 2131230736;
			
			// aapt resource value: 0x7F080011
			public static int exo_download_completed = 2131230737;
			
			// aapt resource value: 0x7F080012
			public static int exo_download_description = 2131230738;
			
			// aapt resource value: 0x7F080013
			public static int exo_download_downloading = 2131230739;
			
			// aapt resource value: 0x7F080014
			public static int exo_download_failed = 2131230740;
			
			// aapt resource value: 0x7F080015
			public static int exo_download_notification_channel_name = 2131230741;
			
			// aapt resource value: 0x7F080016
			public static int exo_download_removing = 2131230742;
			
			// aapt resource value: 0x7F080017
			public static int exo_item_list = 2131230743;
			
			// aapt resource value: 0x7F080018
			public static int exo_media_action_repeat_all_description = 2131230744;
			
			// aapt resource value: 0x7F080019
			public static int exo_media_action_repeat_off_description = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public static int exo_media_action_repeat_one_description = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public static int exo_track_bitrate = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public static int exo_track_mono = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public static int exo_track_resolution = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public static int exo_track_role_alternate = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public static int exo_track_role_closed_captions = 2131230751;
			
			// aapt resource value: 0x7F080020
			public static int exo_track_role_commentary = 2131230752;
			
			// aapt resource value: 0x7F080021
			public static int exo_track_role_supplementary = 2131230753;
			
			// aapt resource value: 0x7F080022
			public static int exo_track_selection_auto = 2131230754;
			
			// aapt resource value: 0x7F080023
			public static int exo_track_selection_none = 2131230755;
			
			// aapt resource value: 0x7F080024
			public static int exo_track_selection_title_audio = 2131230756;
			
			// aapt resource value: 0x7F080025
			public static int exo_track_selection_title_text = 2131230757;
			
			// aapt resource value: 0x7F080026
			public static int exo_track_selection_title_video = 2131230758;
			
			// aapt resource value: 0x7F080027
			public static int exo_track_stereo = 2131230759;
			
			// aapt resource value: 0x7F080028
			public static int exo_track_surround = 2131230760;
			
			// aapt resource value: 0x7F080029
			public static int exo_track_surround_5_point_1 = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public static int exo_track_surround_7_point_1 = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public static int exo_track_unknown = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public static int hello = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public static int status_bar_notification_info_overflow = 2131230765;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public static int ExoMediaButton = 2131296256;
			
			// aapt resource value: 0x7F090001
			public static int ExoMediaButton_FastForward = 2131296257;
			
			// aapt resource value: 0x7F090002
			public static int ExoMediaButton_Next = 2131296258;
			
			// aapt resource value: 0x7F090003
			public static int ExoMediaButton_Pause = 2131296259;
			
			// aapt resource value: 0x7F090004
			public static int ExoMediaButton_Play = 2131296260;
			
			// aapt resource value: 0x7F090005
			public static int ExoMediaButton_Previous = 2131296261;
			
			// aapt resource value: 0x7F090006
			public static int ExoMediaButton_Rewind = 2131296262;
			
			// aapt resource value: 0x7F090007
			public static int ExoMediaButton_VR = 2131296263;
			
			// aapt resource value: 0x7F090008
			public static int TextAppearance_Compat_Notification = 2131296264;
			
			// aapt resource value: 0x7F090009
			public static int TextAppearance_Compat_Notification_Info = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public static int TextAppearance_Compat_Notification_Info_Media = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public static int TextAppearance_Compat_Notification_Line2 = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public static int TextAppearance_Compat_Notification_Line2_Media = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public static int TextAppearance_Compat_Notification_Media = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public static int TextAppearance_Compat_Notification_Time = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public static int TextAppearance_Compat_Notification_Time_Media = 2131296271;
			
			// aapt resource value: 0x7F090010
			public static int TextAppearance_Compat_Notification_Title = 2131296272;
			
			// aapt resource value: 0x7F090011
			public static int TextAppearance_Compat_Notification_Title_Media = 2131296273;
			
			// aapt resource value: 0x7F090012
			public static int Widget_Compat_NotificationActionContainer = 2131296274;
			
			// aapt resource value: 0x7F090013
			public static int Widget_Compat_NotificationActionText = 2131296275;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F01001A }
			public static int[] AspectRatioFrameLayout = new int[] {
					2130771994};
			
			// aapt resource value: 0
			public static int AspectRatioFrameLayout_resize_mode = 0;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010002 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771970};
			
			// aapt resource value: 2
			public static int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public static int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public static int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010004,0x7F010005,0x7F010016,0x7F010017,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010027,0x7F010029 }
			public static int[] DefaultTimeBar = new int[] {
					2130771968,
					2130771969,
					2130771972,
					2130771973,
					2130771990,
					2130771991,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772007,
					2130772009};
			
			// aapt resource value: 0
			public static int DefaultTimeBar_ad_marker_color = 0;
			
			// aapt resource value: 1
			public static int DefaultTimeBar_ad_marker_width = 1;
			
			// aapt resource value: 2
			public static int DefaultTimeBar_bar_height = 2;
			
			// aapt resource value: 3
			public static int DefaultTimeBar_buffered_color = 3;
			
			// aapt resource value: 4
			public static int DefaultTimeBar_played_ad_marker_color = 4;
			
			// aapt resource value: 5
			public static int DefaultTimeBar_played_color = 5;
			
			// aapt resource value: 6
			public static int DefaultTimeBar_scrubber_color = 6;
			
			// aapt resource value: 7
			public static int DefaultTimeBar_scrubber_disabled_size = 7;
			
			// aapt resource value: 8
			public static int DefaultTimeBar_scrubber_dragged_size = 8;
			
			// aapt resource value: 9
			public static int DefaultTimeBar_scrubber_drawable = 9;
			
			// aapt resource value: 10
			public static int DefaultTimeBar_scrubber_enabled_size = 10;
			
			// aapt resource value: 11
			public static int DefaultTimeBar_touch_target_height = 11;
			
			// aapt resource value: 12
			public static int DefaultTimeBar_unplayed_color = 12;
			
			// aapt resource value: { 0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F }
			public static int[] FontFamily = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010009,0x7F010010,0x7F010011,0x7F010012,0x7F010028 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771977,
					2130771984,
					2130771985,
					2130771986,
					2130772008};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public static int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public static int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public static int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public static int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public static int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public static int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public static int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public static int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public static int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public static int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public static int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public static int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public static int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public static int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public static int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public static int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public static int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public static int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public static int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public static int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public static int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010004,0x7F010005,0x7F010006,0x7F010008,0x7F010016,0x7F010017,0x7F010019,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010022,0x7F010023,0x7F010026,0x7F010027,0x7F010029 }
			public static int[] PlayerControlView = new int[] {
					2130771968,
					2130771969,
					2130771972,
					2130771973,
					2130771974,
					2130771976,
					2130771990,
					2130771991,
					2130771993,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772002,
					2130772003,
					2130772006,
					2130772007,
					2130772009};
			
			// aapt resource value: 0
			public static int PlayerControlView_ad_marker_color = 0;
			
			// aapt resource value: 1
			public static int PlayerControlView_ad_marker_width = 1;
			
			// aapt resource value: 2
			public static int PlayerControlView_bar_height = 2;
			
			// aapt resource value: 3
			public static int PlayerControlView_buffered_color = 3;
			
			// aapt resource value: 4
			public static int PlayerControlView_controller_layout_id = 4;
			
			// aapt resource value: 5
			public static int PlayerControlView_fastforward_increment = 5;
			
			// aapt resource value: 6
			public static int PlayerControlView_played_ad_marker_color = 6;
			
			// aapt resource value: 7
			public static int PlayerControlView_played_color = 7;
			
			// aapt resource value: 8
			public static int PlayerControlView_repeat_toggle_modes = 8;
			
			// aapt resource value: 9
			public static int PlayerControlView_rewind_increment = 9;
			
			// aapt resource value: 10
			public static int PlayerControlView_scrubber_color = 10;
			
			// aapt resource value: 11
			public static int PlayerControlView_scrubber_disabled_size = 11;
			
			// aapt resource value: 12
			public static int PlayerControlView_scrubber_dragged_size = 12;
			
			// aapt resource value: 13
			public static int PlayerControlView_scrubber_drawable = 13;
			
			// aapt resource value: 14
			public static int PlayerControlView_scrubber_enabled_size = 14;
			
			// aapt resource value: 15
			public static int PlayerControlView_show_shuffle_button = 15;
			
			// aapt resource value: 16
			public static int PlayerControlView_show_timeout = 16;
			
			// aapt resource value: 17
			public static int PlayerControlView_time_bar_min_update_interval = 17;
			
			// aapt resource value: 18
			public static int PlayerControlView_touch_target_height = 18;
			
			// aapt resource value: 19
			public static int PlayerControlView_unplayed_color = 19;
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010021,0x7F010022,0x7F010023,0x7F010024,0x7F010025,0x7F010026,0x7F010027,0x7F010029,0x7F01002A,0x7F01002B,0x7F01002C }
			public static int[] PlayerView = new int[] {
					2130771968,
					2130771969,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772009,
					2130772010,
					2130772011,
					2130772012};
			
			// aapt resource value: 0
			public static int PlayerView_ad_marker_color = 0;
			
			// aapt resource value: 1
			public static int PlayerView_ad_marker_width = 1;
			
			// aapt resource value: 2
			public static int PlayerView_auto_show = 2;
			
			// aapt resource value: 3
			public static int PlayerView_bar_height = 3;
			
			// aapt resource value: 4
			public static int PlayerView_buffered_color = 4;
			
			// aapt resource value: 5
			public static int PlayerView_controller_layout_id = 5;
			
			// aapt resource value: 6
			public static int PlayerView_default_artwork = 6;
			
			// aapt resource value: 7
			public static int PlayerView_fastforward_increment = 7;
			
			// aapt resource value: 8
			public static int PlayerView_hide_during_ads = 8;
			
			// aapt resource value: 9
			public static int PlayerView_hide_on_touch = 9;
			
			// aapt resource value: 10
			public static int PlayerView_keep_content_on_player_reset = 10;
			
			// aapt resource value: 11
			public static int PlayerView_played_ad_marker_color = 11;
			
			// aapt resource value: 12
			public static int PlayerView_played_color = 12;
			
			// aapt resource value: 13
			public static int PlayerView_player_layout_id = 13;
			
			// aapt resource value: 14
			public static int PlayerView_repeat_toggle_modes = 14;
			
			// aapt resource value: 15
			public static int PlayerView_resize_mode = 15;
			
			// aapt resource value: 16
			public static int PlayerView_rewind_increment = 16;
			
			// aapt resource value: 17
			public static int PlayerView_scrubber_color = 17;
			
			// aapt resource value: 18
			public static int PlayerView_scrubber_disabled_size = 18;
			
			// aapt resource value: 19
			public static int PlayerView_scrubber_dragged_size = 19;
			
			// aapt resource value: 20
			public static int PlayerView_scrubber_drawable = 20;
			
			// aapt resource value: 21
			public static int PlayerView_scrubber_enabled_size = 21;
			
			// aapt resource value: 22
			public static int PlayerView_show_buffering = 22;
			
			// aapt resource value: 23
			public static int PlayerView_show_shuffle_button = 23;
			
			// aapt resource value: 24
			public static int PlayerView_show_timeout = 24;
			
			// aapt resource value: 25
			public static int PlayerView_shutter_background_color = 25;
			
			// aapt resource value: 26
			public static int PlayerView_surface_type = 26;
			
			// aapt resource value: 27
			public static int PlayerView_time_bar_min_update_interval = 27;
			
			// aapt resource value: 28
			public static int PlayerView_touch_target_height = 28;
			
			// aapt resource value: 29
			public static int PlayerView_unplayed_color = 29;
			
			// aapt resource value: 30
			public static int PlayerView_use_artwork = 30;
			
			// aapt resource value: 31
			public static int PlayerView_use_controller = 31;
			
			// aapt resource value: 32
			public static int PlayerView_use_sensor_rotation = 32;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
